# Generated by Django 5.0.1 on 2024-03-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakevariant',
            name='weight_in_kg',
            field=models.DecimalField(choices=[(0.5, '0.5 kg'), (1, '1 kg'), (1.5, '1.5 kg'), (2, '2 kg'), (3, '3 kg'), (4, '4 kg'), (5, '5 kg')], decimal_places=2, default=1, max_digits=10),
        ),
    ]
