# Generated by Django 5.0.1 on 2024-03-25 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0002_alter_cakevariant_weight_in_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='is_order_placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='occation_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakeshop.occasion'),
        ),
    ]
