# Generated by Django 5.0.1 on 2024-03-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0004_basketitem_flavour_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
