# Generated by Django 5.0.1 on 2024-03-26 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0005_basketitem_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='basket_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitem', to='cakeshop.basket'),
        ),
    ]
